name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          skip-cache: true

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.14'
          - 'stable'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      env:
        CLOUDMAILIN_SMTP_URL: ${{ secrets.CLOUDMAILIN_SMTP_URL }}
      run: go test -v ./...
